routes/web.php
<?php
# Backend Controllers
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Backend\BackendAboutUsController;
use App\Http\Controllers\Backend\BackendAchievementController;
use App\Http\Controllers\Backend\BackendPartnerController;
use App\Http\Controllers\Backend\BackendProductController;
use App\Http\Controllers\Backend\BackendSlidersController;
use App\Http\Controllers\Backend\HotelController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\BackendAdminController;
use App\Http\Controllers\Backend\BackendNotificationsController;
use App\Http\Controllers\Backend\BackendHelperController;
use App\Http\Controllers\Backend\BackendTestController;
use App\Http\Controllers\Backend\BackendProfileController;
use App\Http\Controllers\Backend\BackendArticleController;
use App\Http\Controllers\Backend\BackendArticleCommentController;
use App\Http\Controllers\Backend\BackendSiteMapController;
use App\Http\Controllers\Backend\BackendSettingController;
use App\Http\Controllers\Backend\BackendContactController;
use App\Http\Controllers\Backend\BackendCategoryController;
use App\Http\Controllers\Backend\BackendRedirectionController;
use App\Http\Controllers\Backend\BackendUserController;
use App\Http\Controllers\Backend\BackendTrafficsController;
use App\Http\Controllers\Backend\BackendPageController;
use App\Http\Controllers\Backend\BackendMenuController;
use App\Http\Controllers\Backend\BackendMenuLinkController;
use App\Http\Controllers\Backend\BackendFileController;
use App\Http\Controllers\Backend\BackendFaqController;
use App\Http\Controllers\Backend\BackendContactReplyController;
use App\Http\Controllers\Backend\BackendAnnouncementController;
use App\Http\Controllers\Backend\BackendPermissionController;
use App\Http\Controllers\Backend\BackendUserPermissionController;
use App\Http\Controllers\Backend\BackendUserRoleController;
use App\Http\Controllers\Backend\BackendRoleController;
use App\Http\Controllers\Backend\BackendTagController;
use App\Http\Controllers\Backend\BackendPluginController;


# Frontend Controllers
use App\Http\Controllers\FrontController;
use App\Http\Controllers\FrontendProfileController;

Auth::routes(['register' => false]);
Auth::routes();

Route::get('/lang/{lang}', [FrontController::class,'lang'])->name('lang');


Route::get('/', [FrontController::class,'index'])->name('home');
Route::get('/about-us', [FrontController::class,'about_us'])->name('about-us');
Route::get('/contact-us', [FrontController::class,'contact_us'])->name('contact-us');
Route::post('/contact-us', [FrontController::class,'contact_us_post'])->name('site.contact');
Route::get('/cat-products', [FrontController::class,'catProducts'])->name('cat.products');
Route::get('/partners', [FrontController::class,'partners'])->name('partners');
Route::get('/products/{id?}', [FrontController::class,'products'])->name('products');


//e6dJJAHfdrHgBae

//Route::prefix('dashboard')->middleware(['auth','ActiveAccount','verified'])->name('user.')->group(function () {
//    Route::get('/',                           [FrontendProfileController::class,'dashboard'])->name('dashboard');
//    Route::get('/support',                    [FrontendProfileController::class,'support'])->name('support');
//    Route::get('/support/create-ticket',      [FrontendProfileController::class,'create_ticket'])->name('create-ticket');
//    Route::post('/support/create-ticket',     [FrontendProfileController::class,'store_ticket'])->name('store-ticket');
//    Route::get('/support/{ticket}',           [FrontendProfileController::class,'ticket'])->name('ticket');
//    Route::post('/support/{ticket}/reply',    [FrontendProfileController::class,'reply_ticket'])->name('reply-ticket');
//    Route::get('/notifications',              [FrontendProfileController::class,'notifications'])->name('notifications');
//    Route::prefix('profile')->name('profile.')->group(function () {
//        Route::get('/settings',               [FrontendProfileController::class,'profile_edit'])->name('edit');
//        Route::put('/update',                 [FrontendProfileController::class,'profile_update'])->name('update');
//        Route::put('/update-password',        [FrontendProfileController::class,'profile_update_password'])->name('update-password');
//        Route::put('/update-email',           [FrontendProfileController::class,'profile_update_email'])->name('update-email');
//    });
//});


Route::get('admin/',[BackendAdminController::class,'index'])->name('index')->middleware(['auth','ActiveAccount']);

Route::prefix('admin')->middleware(['auth','ActiveAccount'])->name('admin.')->group(function () {

    Route::get('admin/',[BackendAdminController::class,'index'])->name('index');
    Route::middleware('auth')->group(function () {
        Route::resource('announcements',  BackendAnnouncementController::class);
        Route::resource('files',          BackendFileController::class);
        Route::post('contacts/resolve',             [BackendContactController::class,'resolve'])->name('contacts.resolve');
        Route::resource('contacts',       BackendContactController::class);
        Route::resource('menus',          BackendMenuController::class);
        Route::get('users/{user}/access',           [BackendUserController::class,'access'])->name('users.access');
        Route::resource('users',          BackendUserController::class);
        Route::resource('roles',          BackendRoleController::class);
        Route::get('user-roles/{user}',             [BackendUserRoleController::class,'index'])->name('users.roles.index');
        Route::put('user-roles/{user}',             [BackendUserRoleController::class,'update'])->name('users.roles.update');
        Route::resource('articles',       BackendArticleController::class);
        Route::post('article-comments/change_status',[BackendArticleCommentController::class,'change_status'])->name('article-comments.change_status');
        Route::resource('article-comments',BackendArticleCommentController::class);
        Route::resource('pages',BackendPageController::class);
        Route::resource('tags',BackendTagController::class);
        Route::resource('contact-replies',BackendContactReplyController::class);
        Route::post('faqs/order',[BackendFaqController::class,'order'])->name('faqs.order');
        Route::resource('faqs',BackendFaqController::class);
        Route::post('menu-links/get-type',[BackendMenuLinkController::class,'getType'])->name('menu-links.get-type');
        Route::post('menu-links/order',[BackendMenuLinkController::class,'order'])->name('menu-links.order');
        Route::resource('menu-links',BackendMenuLinkController::class);
        Route::resource('categories',BackendCategoryController::class);
        Route::resource('sliders',   BackendSlidersController::class);
        Route::resource('products',   BackendProductController::class);
        Route::resource('partners',   BackendPartnerController::class);
        Route::resource('achievements',   BackendAchievementController::class);
        Route::resource('AboutUs',   BackendAboutUsController::class);
        Route::resource('hotels',HotelController::class);

        Route::get('hotels/{hotels_image_id}/delete',[HotelController::class,'imageDestroy'])->name('delete.hotels.image');


        Route::resource('redirections',BackendRedirectionController::class);
        Route::get('traffics',[BackendTrafficsController::class,'index'])->name('traffics.index');
        Route::get('traffics/logs',[BackendTrafficsController::class,'logs'])->name('traffics.logs');
        Route::get('error-reports',[BackendTrafficsController::class,'error_reports'])->name('traffics.error-reports');
        Route::get('error-reports/{report}',[BackendTrafficsController::class,'error_report'])->name('traffics.error-report');

        Route::prefix('settings')->name('settings.')->group(function () {
            Route::get('/',[BackendSettingController::class,'index'])->name('index');
            Route::put('/update',[BackendSettingController::class,'update'])->name('update');
        });
    });

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[BackendHelperController::class,'upload_image'])->name('image');
        Route::post('/file',[BackendHelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[BackendHelperController::class,'remove_files'])->name('remove-file');
    });

    Route::prefix('plugins')->name('plugins.')->group(function(){
        Route::get('/',[BackendPluginController::class,'index'])->name('index');
        Route::get('/create',[BackendPluginController::class,'create'])->name('create');
        Route::post('/create',[BackendPluginController::class,'store'])->name('store');
        Route::post('/{plugin}/activate',[BackendPluginController::class,'activate'])->name('activate');
        Route::post('/{plugin}/deactivate',[BackendPluginController::class,'deactivate'])->name('deactivate');
        Route::post('/{plugin}/delete',[BackendPluginController::class,'delete'])->name('delete');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/',[BackendProfileController::class,'index'])->name('index');
        Route::get('/edit',[BackendProfileController::class,'edit'])->name('edit');
        Route::put('/update',[BackendProfileController::class,'update'])->name('update');
        Route::put('/update-password',[BackendProfileController::class,'update_password'])->name('update-password');
        Route::put('/update-email',[BackendProfileController::class,'update_email'])->name('update-email');
    });

    Route::prefix('notifications')->name('notifications.')->group(function () {
        Route::get('/',[BackendNotificationsController::class,'index'])->name('index');
        Route::get('/ajax',[BackendNotificationsController::class,'ajax'])->name('ajax');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $guarded = ['id','created_at','updated_at'];
    
    public function getRouteKeyName(){
        return 'slug';
    }
}

resources/views/admin/tags/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
    <div class="col-12 col-lg-12 p-0 ">
        <form id="validate-form" class="row" enctype="multipart/form-data" method="POST" action="{{route('admin.tags.store')}}">
            @csrf
            <div class="col-12 col-lg-8 p-0 main-box">
                <div class="col-12 px-0">
                    <div class="col-12 px-3 py-3">
                        <span class="fas fa-info-circle"></span> إضافة جديد
                    </div>
                    <div class="col-12 divider" style="min-height: 2px;"></div>
                </div>
                <div class="col-12 p-3 row">
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            اسم المهارة 
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="tag_name" required maxlength="190" class="form-control" value="{{old('tag_name',$tag??"")}}" placeholder="مثال: تصميم الجرافيك">
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            الاسم باللغة العربية
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="arabic_name" required maxlength="190" class="form-control" value="{{old('arabic_name',$tag??"")}}" placeholder="مثال: التصميم الجرافيكي">
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            الاسم باللغة الانجليزية 
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="english_name" required maxlength="190" class="form-control" value="{{old('english_name',$tag??"")}}" placeholder="مثال: Graphic Design">
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            رمز المهارة
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="slug" required maxlength="190" class="form-control" value="{{old('slug',$tag??"")}}" placeholder="مثال: graphic-design">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 p-3">
                <button class="btn btn-success" id="submitEvaluation">حفظ</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
    <div class="col-12 col-lg-12 p-0 ">
        <form id="validate-form" class="row" enctype="multipart/form-data" method="POST" action="{{route('admin.tags.update',$tag)}}">
            @csrf
            @method("PUT")
            <div class="col-12 col-lg-8 p-0 main-box">
                <div class="col-12 px-0">
                    <div class="col-12 px-3 py-3">
                        <span class="fas fa-info-circle"></span> تعديل
                    </div>
                    <div class="col-12 divider" style="min-height: 2px;"></div>
                </div>
             
                
                <div class="col-12 p-3 row">
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            اسم المهارة 
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="tag_name" required maxlength="190" class="form-control" value="{{old('tag_name',$tag??"")}}" placeholder="مثال: تصميم الجرافيك">
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            الاسم باللغة العربية
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="arabic_name" required maxlength="190" class="form-control" value="{{old('arabic_name',$tag??"")}}" placeholder="مثال: التصميم الجرافيكي">
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            الاسم باللغة الانجليزية 
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="english_name" required maxlength="190" class="form-control" value="{{old('english_name',$tag??"")}}" placeholder="مثال: Graphic Design">
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 p-2">
                        <div class="col-12">
                            رمز المهارة
                        </div>
                        <div class="col-12 pt-3">
                            <input type="text" name="slug" required maxlength="190" class="form-control" value="{{old('slug',$tag??"")}}" placeholder="مثال: graphic-design">
                        </div>
                    </div>
                </div>
                    
              
            </div>
            <div class="col-12 p-3">
                <button class="btn btn-success" id="submitEvaluation">حفظ</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
	<div class="col-12 col-lg-12 p-0 main-box">

		<div class="col-12 px-0">
			<div class="col-12 p-0 row">
				<div class="col-12 col-lg-4 py-3 px-3">
					<span class="fas fa-tags"></span> عرض الكل
				</div>
				<div class="col-12 col-lg-4 p-2">
				</div>
				<div class="col-12 col-lg-4 p-2 text-lg-end">
					@can('tags-create')
					<a href="{{route('admin.tags.create')}}">
					<span class="btn btn-primary"><span class="fas fa-plus"></span> إضافة جديد</span>
					</a>
					@endcan
				</div>
			</div>
			<div class="col-12 divider" style="min-height: 2px;"></div>
		</div>

		<div class="col-12 py-2 px-2 row">
			<div class="col-12 col-lg-4 p-2">
				<form method="GET">
					<input type="text" name="q" class="form-control" placeholder="بحث ... " value="{{request()->get('q')}}">
				</form>
			</div>
		</div>
		<div class="col-12 p-3" style="overflow:auto">
			<div class="col-12 p-0" style="min-width:1100px;">


			<table class="table table-bordered  table-hover">
				<thead>
					<tr>
						<th>#</th>
						<th>الاسم</th>
						<th>الرمز</th>
						<th>تحكم</th>
					</tr>
				</thead>
				<tbody id="sortable-table">
					@foreach($tags as $tag)
					<tr >
						<td>{{$tag->id}}</td>
						<td>{{$tag->tag_name}}</td>
						<td>{{$tag->slug}}</td>

						<td style="width: 270px;">
							@can('tags-update')
							<a href="{{route('admin.tags.edit',$tag)}}">
								<span class="btn  btn-outline-success btn-sm font-1 mx-1">
									<span class="fas fa-wrench "></span> تعديل
								</span>
							</a>
							@endcan
							@can('tags-delete')
							<form method="POST" action="{{route('admin.tags.destroy',$tag)}}" class="d-inline-block">@csrf @method("DELETE")
								<button class="btn  btn-outline-danger btn-sm font-1 mx-1" onclick="var result = confirm('هل أنت متأكد من عملية الحذف ؟');if(result){}else{event.preventDefault()}">
									<span class="fas fa-trash "></span> حذف
								</button>
							</form>
							@endcan
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			</div>
		</div>
		<div class="col-12 p-3">
			{{$tags->appends(request()->query())->render()}}
		</div>
	</div>
</div>
@endsection